language: php
php:
    - 5.6
    - 5.5
    - 5.4
    - 5.3

env:
    - LIBZOOKEEPER_VERSION=3.5.0-alpha
    - LIBZOOKEEPER_VERSION=3.4.6

before_script:
    - ./.travis/install_libzookeeper.sh $LIBZOOKEEPER_VERSION

script:
    - ./.travis/build.sh $LIBZOOKEEPER_VERSION
